#!/bin/bash
################################################################################
# A part of TINKTEP, an interface between ONETEP and TINKER.                   #
# Jacek Dziedzic, University of Southampton, May-December 2015.                #
################################################################################

################################################################################
# *** xyz_traj ***
# Combines multiple .xyz files into one trajectory .xyz file.
#
# Technically TINKER's 'archive' offers the same functionality, but it
# preserves BBox lines, which confuse VMD later on. This script drops the
# BBox lines from all frames.
#
# v1.01
# Jacek Dziedzic, May-December 2015.
################################################################################
# Revision history:
# v1.00 2016.01.?? -- Initial version.
# v1.01 2016.01.25 -- Cleanup, use of xyz_bbox_line, error codes.
################################################################################

myname="xyz_traj"

#-------------------------------------------------------------------------------
# Aborts, printing a message and returning an error code.
#-------------------------------------------------------------------------------
function error() {
  echo "!!! $myname: ERROR #$2: $1. Aborting!" >&2
  exit $2
}
#-------------------------------------------------------------------------------

################################################################################
# Error codes
################################################################################
err_improper_invocation=101
err_bbox=102

################################################################################
# main()
################################################################################

if [ $# -ne 4 ]; then
  error "Improper invocation. Supply a filename root and three numbers: the first and last snapshot indices, and an increment" $err_improper_invocation
fi

root=$1
n0=$2
n1=$3
dn=$4
outxyzf=$root"_traj.xyz"

rm -f $outxyzf
for n in `seq $n0 $dn $n1`; do
  ext=`echo $n | awk '{printf("%03d",$1)}'`
  inxyzf=$root.$ext
  echo "Examining $inxyzf: " >&2
  # See if there's a BBox line in the .xyz file, it needs to be dropped in the trajectory, as it confuses VMD if present in multi-snapshot files.
  bbox_line=`xyz_bbox_line $inxyzf` || error "Could not verify the presence of, or parse, the BBox line in the .xyz file $inxyzf" $err_bbox
  bbox_line_present=`echo $bbox_line | awk '{print ($4 > 0)}'`
  head -n 1 $inxyzf >>$outxyzf
  let "firstatomline=2+bbox_line_present"
  tail -n +$firstatomline $inxyzf >>$outxyzf
done
