#!/bin/bash
##########################################################################################
# dxgeom -- provide details about the geometry of a .dx file
#
# v1.00 2009.11.20 jd, first version
# v1.01 2010.02.05 jd, cleans up properly
##########################################################################################
##########################################################################################
ver="1.01"
##########################################################################################

improper_invocation() {
  echo "Improper invocation. Supply one argument (name of the dx file). ">&2
  exit 101
}

echo >&2
echo "*** dxgeom v$ver. Provides details about a geometry of a .dx file" >&2
echo "                  2009.11 Jacek Dziedzic, jack.erede@gmail.com" >&2
echo >&2

if [ $# -ne 1 ]; then
  improper_invocation
fi 

f="$1"
header1="\$header1"

echo "Reading from $f." >&2

head -n 20 $f | grep "^[a-z]" >$header1

# determine the voxel volume
hxhyhz=`cat $header1 | grep "^delta" | awk '{print $(NR+1)}' | tr "\n" " "`
voxelvolume=`echo $hxhyhz | awk '{print $1*$2*$3}'`

# determine the origin
origin=`cat $header1 | grep "origin" | awk '{printf("%g %g %g", $2,$3,$4) }'`

# determine nvoxels
nxnynz=`cat $header1 | grep "gridconnections" | awk '{print $6,$7,$8}'`
nvoxels=`echo $nxnynz | awk '{print $1*$2*$3}'`

# determine where the box ends
boxend=`echo $origin $nxnynz $hxhyhz | awk '{printf("%g %g %g", $1+$4*$7,$2+$5*$8,$3+$6*$9)}'`
boxlen=`echo $origin $boxend | awk '{printf("%g %g %g", $4-$1, $5-$2, $6-$3)}'`

# determine the box centre
boxcentre=`echo $origin $boxend | awk '{printf("%g %g %g",0.5*($1+$4),0.5*($2+$5),0.5*($3+$6))}'`

# determine the box volume
boxvolume1=`echo $boxlen | awk '{print $1*$2*$3}'` # from box lengths
boxvolume2=`echo $voxelvolume $nvoxels | awk '{print $1*$2}'` # voxel_volume * nvoxels

echo
echo "origin: $origin"
echo "boxend: $boxend"
echo "boxlen: $boxlen"
echo "boxcentre: $boxcentre"
echo "nxnynz: $nxnynz"
echo "nvoxels: $nvoxels"
echo "hxhyhz_[A]: $hxhyhz"
echo "voxel_volume_[A^3]: $voxelvolume"
echo "box_volume_from_lengths_[A^3]: $boxvolume1"
echo "box_volume_from_voxels[A^3]: $boxvolume2"
echo

rm -f $header1
