#!/bin/bash

# Required by 'md2thermo'.
# Finds the maximum absolute value in a file composed of numbers.

if [ $# -gt 1 ]; then
  echo "Improper invocation: supply either no parameters (to read from the stdin) or one parameter -- the input filename."
  exit 129
fi

if [ $# -eq 1 ]; then
  filename="$1"
else
  filename="/dev/stdin"
fi

cat "$filename" | awk 'function abs(x) {if(x>0) return x; else return -x} BEGIN{el=-9e99} {for(i=1;i<=NF;++i) if(abs($i)>el) {el=abs($i); x=i; y=NR;} } END{print el," at row ", y, " col ", x}'

